### ISSUE TITLE
TypeError: buf.charCodeAt is not a function

### ISSUE THREAD

**Issue by XhmikosR** [sindresorhus/is-svg#19]
```
C:\Users\xmr\Desktop\foo>node -v && npm -v
v10.13.0
6.4.1

C:\Users\xmr\Desktop\foo>npm ls is-svg
foo@1.0.0 C:\Users\xmr\Desktop\foo
`-- gulp-imagemin@5.0.0
  `-- imagemin-svgo@7.0.0
    `-- is-svg@3.0.0


[09:45:14] TypeError: buf.charCodeAt is not a function
    at isBinary (C:\Users\xmr\Desktop\foo\node_modules\is-svg\index.js:8:41)
    at module.exports.input (C:\Users\xmr\Desktop\foo\node_modules\is-svg\index.js:20:46)
    at Function.buffer [as svgo] (C:\Users\xmr\Desktop\foo\node_modules\imagemin-svgo\index.js:8:7)
    at gulp.task (C:\Users\xmr\Desktop\foo\gulp\tasks\production\optimize-images.js:15:22)
    at taskWrapper (C:\Users\xmr\Desktop\foo\node_modules\undertaker\lib\set-task.js:13:15)
    at tempTask (C:\Users\xmr\Desktop\foo\node_modules\undertaker-forward-reference\index.js:13:17)
    at bound (domain.js:396:14)
    at runBound (domain.js:409:12)
    at asyncRunner (C:\Users\xmr\Desktop\foo\node_modules\async-done\index.js:55:18)
    at process._tickCallback (internal/process/next_tick.js:61:11)
```

This worked with the previous version so I'm trying to pinpoint the cause.

/CC @sindresorhus for ideas

**Comment by XhmikosR** [comment]
OK probably wrong repo, I should have opened this in imagemin-svgo.
